# Generated by Django 5.0.6 on 2024-07-01 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='description',
            field=models.TextField(default=None, max_length=512, null=True),
        ),
    ]
