# Generated by Django 5.0.6 on 2024-06-26 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_task_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='subject',
            field=models.CharField(choices=[('ALG', 'Algebra'), ('ART', 'Art'), ('BIO', 'Biology'), ('CHE', 'Chemistry'), ('ENG', 'English'), ('GEO', 'Geography'), ('HIS', 'History'), ('PE', 'PE')], default=None, max_length=3, null=True),
        ),
    ]
