# Generated by Django 5.0.6 on 2024-07-08 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_course_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='image',
            field=models.ImageField(default=None, null=True, upload_to='images/'),
        ),
    ]
