# Generated by Django 5.0.6 on 2024-07-11 09:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_tag_remove_course_subject_course_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=512)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('recipients', models.ManyToManyField(to='tasks.student')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcements_by_teacher', to='tasks.teacher')),
            ],
        ),
    ]
