# Generated by Django 5.0.6 on 2024-07-11 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_announcement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcement',
            name='recipients',
        ),
    ]
